/*
 * Note: this file originally auto-generated by mib2c using
 *  $ env MIBS="+DTS-TOOL-SMARTEQ-MIB" mib2c -c mib2c.iterate.conf eqFilterTable
 */
#ifndef EQFILTERTABLE_H
#define EQFILTERTABLE_H

/* function declarations */
void init_eqFilterTable(void);
void initialize_table_eqFilterTable(void);
Netsnmp_Node_Handler eqFilterTable_handler;
Netsnmp_First_Data_Point  eqFilterTable_get_first_data_point;
Netsnmp_Next_Data_Point   eqFilterTable_get_next_data_point;

/* column number definitions for table eqFilterTable */
       #define COLUMN_EQFILTERINDEX		1
       #define COLUMN_EQFILTERFREQUENCY		2
       #define COLUMN_EQFILTERGAIN		3
       #define COLUMN_EQFILTERQ		4
       #define COLUMN_EQFILTERTYPE		5
       #define COLUMN_EQFILTERSTATUS		9
#endif /* EQFILTERTABLE_H */
