/*
 * Note: this file originally auto-generated by mib2c using
 *  $ env MIBS="+DTS-TOOL-SMARTEQ-MIB" mib2c -c mib2c.iterate.conf eqFilterTable
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "eqFilterTable.h"

#include "smarteq_utils.h"

/** Initializes the eqFilterTable module */
void
init_eqFilterTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_eqFilterTable();
}

/*  # Determine the first/last column names */

/** Initialize the eqFilterTable table by defining its contents and how it's structured */
void
initialize_table_eqFilterTable(void)
{
    const oid eqFilterTable_oid[] = {1,3,6,1,4,1,5220,2,101,101};
    const size_t eqFilterTable_oid_len   = OID_LENGTH(eqFilterTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

	DEBUGMSGTL(("eqFilterTable:init", "initializing table eqFilterTable\n"));

    reg = netsnmp_create_handler_registration(
              "eqFilterTable",     eqFilterTable_handler,
              eqFilterTable_oid, eqFilterTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: eqFilterIndex */
                           0);
    table_info->min_column = COLUMN_EQFILTERINDEX;
    table_info->max_column = COLUMN_EQFILTERSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = eqFilterTable_get_first_data_point;
    iinfo->get_next_data_point  = eqFilterTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */

}

    /* Typical data structure for a row entry */
struct eqFilterTable_entry {
    /* Index values */
    u_long eqFilterIndex;

    /* Column values */
    float eqFilterFrequency;
    float old_eqFilterFrequency;
    float eqFilterGain;
    float old_eqFilterGain;
    float eqFilterQ;
    float old_eqFilterQ;
    long eqFilterType;
    long old_eqFilterType;
    long eqFilterStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct eqFilterTable_entry *next;
};

struct eqFilterTable_entry  *eqFilterTable_head = NULL;

/* create a new row in the (unsorted) table */
struct eqFilterTable_entry *
eqFilterTable_createEntry(
                 u_long  eqFilterIndex,
                 float  eqFilterFrequency,
                 float  eqFilterGain,
                 float  eqFilterQ,
                 long   eqFilterType
                ) {
    struct eqFilterTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct eqFilterTable_entry);
    if (!entry)
        return NULL;

    entry->eqFilterIndex = eqFilterIndex;
    entry->eqFilterFrequency = eqFilterFrequency;
    entry->eqFilterGain = eqFilterGain;
    entry->eqFilterQ = eqFilterQ;
    entry->eqFilterType = eqFilterType;
    entry->eqFilterStatus = RS_ACTIVE;
	entry->next = eqFilterTable_head;
    eqFilterTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
eqFilterTable_removeEntry( struct eqFilterTable_entry *entry ) {
    struct eqFilterTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = eqFilterTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        eqFilterTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
eqFilterTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
	size_t number_eq_filters = get_number_eq_filters();
	double frequency, gain, q;
	int type;

	while (eqFilterTable_head)
	{ 
		eqFilterTable_removeEntry(eqFilterTable_head);
	}

	for (size_t i = 0; i < number_eq_filters; i++)
	{
		get_eq_filter_parameters(i, &frequency, &gain, &q, &type);

		eqFilterTable_createEntry(i, frequency, gain, q, type);
	}

	*my_loop_context = eqFilterTable_head;
    return eqFilterTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
eqFilterTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct eqFilterTable_entry *entry = (struct eqFilterTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->eqFilterIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the eqFilterTable table */
int
eqFilterTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    int      ret;
	netsnmp_request_info       *request;
	netsnmp_table_request_info *table_info;
    struct eqFilterTable_entry          *table_entry;
    struct eqFilterTable_entry          *table_row;
    double   frequency, gain, q;
    int      type;

    DEBUGMSGTL(("eqFilterTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct eqFilterTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EQFILTERINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->eqFilterIndex);
                break;
            case COLUMN_EQFILTERFREQUENCY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OPAQUE_FLOAT,
                                          &(table_entry->eqFilterFrequency),
                                          sizeof(table_entry->eqFilterFrequency));
                break;
            case COLUMN_EQFILTERGAIN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
				snmp_set_var_typed_value( request->requestvb, ASN_OPAQUE_FLOAT,
                                          &(table_entry->eqFilterGain),
                                          sizeof(table_entry->eqFilterGain));
                break;
            case COLUMN_EQFILTERQ:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
				snmp_set_var_typed_value( request->requestvb, ASN_OPAQUE_FLOAT,
                                          &(table_entry->eqFilterQ),
                                          sizeof(table_entry->eqFilterQ));
                break;
            case COLUMN_EQFILTERTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->eqFilterType);
                break;
            case COLUMN_EQFILTERSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->eqFilterStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct eqFilterTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EQFILTERFREQUENCY:
                /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OPAQUE_FLOAT, sizeof(table_entry->eqFilterFrequency));
                if ( ret != SNMP_ERR_NOERROR ) {
                    ret = netsnmp_check_vb_type( request->requestvb, ASN_OPAQUE );
                }
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_EQFILTERGAIN:
                /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OPAQUE_FLOAT, sizeof(table_entry->eqFilterGain));
                if ( ret != SNMP_ERR_NOERROR ) {
                    ret = netsnmp_check_vb_type( request->requestvb, ASN_OPAQUE );
                }
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_EQFILTERQ:
                /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OPAQUE_FLOAT, sizeof(table_entry->eqFilterQ));
                if ( ret != SNMP_ERR_NOERROR ) {
                    ret = netsnmp_check_vb_type( request->requestvb, ASN_OPAQUE );
                }
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_EQFILTERTYPE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_EQFILTERSTATUS:
                ret = netsnmp_check_vb_rowstatus(request->requestvb,
                         (table_entry ? RS_ACTIVE : RS_NONEXISTENT ));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        for (request=requests; request; request=request->next) {
            table_entry = (struct eqFilterTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EQFILTERSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
					get_eq_filter_defaults(&frequency, &gain, &q, &type);
					table_row = eqFilterTable_createEntry(
						*table_info->indexes->val.integer,
						frequency, gain, q, type );
                    if (table_row) {
                        netsnmp_insert_iterator_context( request, table_row );
                    } else {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_RESOURCEUNAVAILABLE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_FREE:
        for (request=requests; request; request=request->next) {
            table_entry = (struct eqFilterTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EQFILTERSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        eqFilterTable_removeEntry( table_entry );
                    }
                }
            }
        }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct eqFilterTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EQFILTERFREQUENCY:
                table_entry->old_eqFilterFrequency = table_entry->eqFilterFrequency;
                if (ASN_OPAQUE == request->requestvb->type) {
                    if (request->requestvb->val.string[0]) {
                        table_entry->eqFilterFrequency = atof(request->requestvb->val.string);
                    }
                } else {
                    table_entry->eqFilterFrequency = *request->requestvb->val.floatVal;
                }
                break;
            case COLUMN_EQFILTERGAIN:
                table_entry->old_eqFilterGain = table_entry->eqFilterGain;
                if (ASN_OPAQUE == request->requestvb->type) {
                    if (request->requestvb->val.string[0]) {
                        table_entry->eqFilterGain = atof(request->requestvb->val.string);
                    }
                } else {
                    table_entry->eqFilterGain = *request->requestvb->val.floatVal;
                }
                break;
            case COLUMN_EQFILTERQ:
                table_entry->old_eqFilterQ = table_entry->eqFilterQ;
                if (ASN_OPAQUE == request->requestvb->type) {
                    if (request->requestvb->val.string[0]) {
                        table_entry->eqFilterQ = atof(request->requestvb->val.string);
					}
                } else {
                    table_entry->eqFilterQ = *request->requestvb->val.floatVal;
                }
                break;
            case COLUMN_EQFILTERTYPE:
                table_entry->old_eqFilterType = table_entry->eqFilterType;
                table_entry->eqFilterType     = *request->requestvb->val.integer;
                break;
            }
        }
        /* Check the internal consistency of an active row */
        for (request=requests; request; request=request->next) {
            table_entry = (struct eqFilterTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EQFILTERSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if (add_eq_filter()) {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_INCONSISTENTVALUE );
                        return SNMP_ERR_NOERROR;
                    }
                    break;
                case RS_DESTROY:
                    remove_eq_filter(table_entry->eqFilterIndex);
                }
                break;
			default:
                if (set_eq_filter_parameters(
                        table_entry->eqFilterIndex,
                        table_entry->eqFilterFrequency,
                        table_entry->eqFilterGain,
                        table_entry->eqFilterQ,
                        table_entry->eqFilterType)) {
                    netsnmp_set_request_error( reqinfo, request,
                                               SNMP_ERR_INCONSISTENTVALUE );
                    return SNMP_ERR_NOERROR;
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct eqFilterTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EQFILTERFREQUENCY:
                table_entry->eqFilterFrequency     = table_entry->old_eqFilterFrequency;
                table_entry->old_eqFilterFrequency = 0;
                break;
            case COLUMN_EQFILTERGAIN:
                table_entry->eqFilterGain     = table_entry->old_eqFilterGain;
                table_entry->old_eqFilterGain = 0;
                break;
            case COLUMN_EQFILTERQ:
                table_entry->eqFilterQ     = table_entry->old_eqFilterQ;
                table_entry->old_eqFilterQ = 0;
                break;
            case COLUMN_EQFILTERTYPE:
                table_entry->eqFilterType     = table_entry->old_eqFilterType;
                table_entry->old_eqFilterType = 0;
                break;
            case COLUMN_EQFILTERSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        eqFilterTable_removeEntry( table_row );
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        for (request=requests; request; request=request->next) {
            table_entry = (struct eqFilterTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EQFILTERSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                    table_entry->valid = 1;
                    /* Fall-through */
                case RS_ACTIVE:
                    table_entry->eqFilterStatus = RS_ACTIVE;
                    break;

                case RS_CREATEANDWAIT:
                    table_entry->valid = 1;
                    /* Fall-through */
                case RS_NOTINSERVICE:
                    table_entry->eqFilterStatus = RS_NOTINSERVICE;
                    break;

                case RS_DESTROY:
                    eqFilterTable_removeEntry( table_entry );
                }
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
