/*
 * Note: this file originally auto-generated by mib2c using
 *        $ env MIBS="+DTS-TOOL-SMARTEQ-MIB" mib2c -c mib2c.scalar.conf smarteq
 */
#ifndef SMARTEQ_H
#define SMARTEQ_H

/* function declarations */
void init_smarteq(void);
Netsnmp_Node_Handler handle_toolVersion;
Netsnmp_Node_Handler handle_snmpEnabled;
Netsnmp_Node_Handler handle_analysisEnabled;
Netsnmp_Node_Handler handle_timeAnalysisEnabled;
Netsnmp_Node_Handler handle_saveWavFilesEnabled;
Netsnmp_Node_Handler handle_numberOfMicrophones;
Netsnmp_Node_Handler handle_microphoneSelected;

#endif /* SMARTEQ_H */
